### PR TITLE
fix: update docs for linux install

### PR DESCRIPTION
**Pull request by nvtkaszpir**
**What type of PR is this?**

documentation

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

I have added some missing steps in the installation.
Fixes minor formatting issues.

**Will this break upgrades or downgrades?**

No.

**Does this PR introduce any user-facing change?**:
Just documentation updates, added missing steps.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rchincha** [comment]
@nvtkaszpir what is the goal of this PR? whitespacing?

**Comment by nvtkaszpir** [comment]
@rchincha as stated in PR description

1. add missing steps in bare metal installation such as: 
- better order of installing zot with sudo wget
- moving line related to chmodding and chowning downloaded binary just after downloading binary
- chowning /etc/zot dir instead of just the config file
- systemd daemon-reload after adding new unit file
- using zot verify after editing zot config

2. Fix some white spaces or new lines
- some of them made markdown preview not working in editors
- trimming too long lines.

I see.Inneed to do some other things as well as I see checks are failing. I'll do it in the evening.

**Review by andaaron — APPROVED** [review]
LGTM

**Review by mbshields — APPROVED** [review]
lgtm

**Comment by nvtkaszpir** [comment]
Updated commit message to be compatible with commit message style

**Comment by rchincha** [comment]
> Checking commit messages against "^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?(!)?(: (.*\s*)*))"...
- failed: "Update docs for linux install

Start your commit msg with "fix: update docs for linux install"

**Comment by nvtkaszpir** [comment]
> > Checking commit messages against "^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)((.+))?(!)?(: (._\s_)*))"...
> 
> * failed: "Update docs for linux install
> 
> @nvtkaszpir Pls start your commit msg with "fix: update docs for linux install"

yeah, totally forgot that PR title goes as commit message, fixed

**Comment by rchincha** [comment]
> > > Checking commit messages against "^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)((.+))?(!)?(: (._\s_)*))"...
> > 
> > 
> > 
> > * failed: "Update docs for linux install
> > 
> > @nvtkaszpir Pls start your commit msg with "fix: update docs for linux install"
> 
> yeah, totally forgot that PR title goes as commit message, fixed

Not the title, the actual commit msg.
https://github.com/project-zot/project-zot.github.io/pull/159/commits/38160dfe26d026254d07aa6da74fbd5ab36168d3
First line of the msg should be 
 "fix: update docs for linux install" (for example)

**Comment by nvtkaszpir** [comment]
Arg I just noticed that somehow my commit message was not amended before. Sorry.

**Review by rchincha — APPROVED** [review]
lgtm

**Pull request merged**
